# Generated by Django 4.1 on 2022-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='alt_erradas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='alt_marcada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='texto1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='texto2',
            field=models.TextField(),
        ),
    ]
