# Generated by Django 4.1 on 2022-09-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='id_prova',
            new_name='id_paper',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.TextField()),
                ('answer', models.TextField()),
                ('papers', models.ManyToManyField(through='elefante.PaperQuestion', to='elefante.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elefante.paper'),
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elefante.question'),
        ),
    ]
