# Generated by Django 4.1 on 2022-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0002_alter_paper_alt_erradas_alter_paper_alt_marcada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='correto',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='texto1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='texto2',
            field=models.TextField(blank=True),
        ),
    ]
