# Generated by Django 4.1 on 2022-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0003_alter_paper_correto_alter_paper_texto1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='link',
            field=models.CharField(default='q8B3YyvYmG5yLQva', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='correto',
            field=models.BooleanField(default=True),
        ),
    ]
