# Generated by Django 4.1 on 2022-09-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0004_dados_cadastro_delete_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_cadastro',
            old_name='nome',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='dados_cadastro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
