# Generated by Django 4.1 on 2022-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0005_rename_nome_dados_cadastro_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_cadastro',
            name='senha',
            field=models.IntegerField(),
        ),
    ]
