# Generated by Django 4.1 on 2022-10-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elefante', '0005_alter_prova_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prova',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prova',
            name='link',
            field=models.CharField(default='LalJEqp0NX3w6P6R', max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='DadosCadastro',
        ),
    ]
