# Generated by Django 4.1 on 2022-09-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0008_alter_dados_cadastro_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_cadastro',
            name='senha',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dados_cadastro',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
