# Generated by Django 4.1 on 2022-09-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0009_alter_dados_cadastro_senha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_cadastro',
            old_name='username',
            new_name='nome',
        ),
    ]
