# Generated by Django 4.1 on 2022-09-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0010_rename_username_dados_cadastro_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='login',
            new_name='email',
        ),
    ]
