# Generated by Django 4.1 on 2022-09-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elefante', '0011_rename_login_dados_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
